// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjh4hNpSJmytZ_9uvabBuCw0jo07U8_WA',
    appId: '1:152099001125:web:f0b06bc0ab3110c83600cc',
    messagingSenderId: '152099001125',
    projectId: 'feedbackapp-ff61c',
    authDomain: 'feedbackapp-ff61c.firebaseapp.com',
    storageBucket: 'feedbackapp-ff61c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKb664pUpS5lpKeNC8Ndz8TdSFdkX2hQ',
    appId: '1:152099001125:android:7418a305627a034c3600cc',
    messagingSenderId: '152099001125',
    projectId: 'feedbackapp-ff61c',
    storageBucket: 'feedbackapp-ff61c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHD1MMz2BU61Vl-lFH_uG15VLEf_EwdpM',
    appId: '1:152099001125:ios:9de5635f866baff23600cc',
    messagingSenderId: '152099001125',
    projectId: 'feedbackapp-ff61c',
    storageBucket: 'feedbackapp-ff61c.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHD1MMz2BU61Vl-lFH_uG15VLEf_EwdpM',
    appId: '1:152099001125:ios:9de5635f866baff23600cc',
    messagingSenderId: '152099001125',
    projectId: 'feedbackapp-ff61c',
    storageBucket: 'feedbackapp-ff61c.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjh4hNpSJmytZ_9uvabBuCw0jo07U8_WA',
    appId: '1:152099001125:web:b67497dee9d2a1cc3600cc',
    messagingSenderId: '152099001125',
    projectId: 'feedbackapp-ff61c',
    authDomain: 'feedbackapp-ff61c.firebaseapp.com',
    storageBucket: 'feedbackapp-ff61c.firebasestorage.app',
  );
}
